apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        resources:
         requests:
           cpu: "250m"
           memory: "256Mi"

         limits:
          cpu: "500m"
          memory: "512Mi"

        startupProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 30
          periodSeconds: 5


        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
           path: /
           port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5